force-app/main/default/objects/Shail_Estimate__c/Shail_Estimate__c.object-meta.xml
<CustomObject>
    <label>Straight Hail Estimate</label>
    <nameField>
        <displayFormat>SHE-{000000000}</displayFormat>
        <label>Straight Hail Estimate ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Straight Hail Estimates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shail_Estimate__c/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Straight Hail Estimates</relationshipLabel>
    <relationshipName>Shail_Estimates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shail_Estimate__c/fields/Estimate_Name__c.field-meta.xml
<CustomField>
    <fullName>Estimate_Name__c</fullName>
    <label>Estimate Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shail_Estimate__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Purchased</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EstimateData.cls
public class EstimateData {
	
    @AuraEnabled
    public static list<Shail_Estimate__c> getEstimateData(){
        return [select Id,Name,Status__c,Estimate_Name__c,Business__c,CreatedDate,LastModifiedDate,LastModifiedBy.Name,CreatedBy.Name from Shail_Estimate__c where CreatedDate = LAST_N_DAYS:365 AND CreatedBy.Name=:UserInfo.getUserName() And (Status__c='Draft' or Status__c='Processing')];
    }
    
    @AuraEnabled
    public static Shail_Estimate__c getEstimateCardData(Id Identifier){
        return [select Id,Name,Status__c,Estimate_Name__c,Business__c,CreatedDate,LastModifiedDate,LastModifiedBy.Name,CreatedBy.Name from Shail_Estimate__c where Id=:Identifier];
    }
}